<a href="https://colab.research.google.com/github/Aakash-Raman/MyCap/blob/master/Numpy%20%26%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [5]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
x + y

array([5, 7, 9])

In [8]:
z = np.full((4,6),7)
print(z)

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1:])

[[4 5 6]
 [7 8 9]]


In [14]:
n = np.arange(6)
print(n)
y = np.arange(6).reshape(2,3)
print(y)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [15]:
!pip install pandas

In [18]:
import pandas as pd
di = {
    'list 1' : [1,2,3,4],
    'list 2' : [5,6,7,8],
    'list 3' : [9,10,11,12]
}

new_panda = pd.DataFrame(di)
print(new_panda)

   list 1  list 2  list 3
0       1       5       9
1       2       6      10
2       3       7      11
3       4       8      12


In [19]:
new_panda.loc[2]

list 1     3
list 2     7
list 3    11
Name: 2, dtype: int64

In [20]:
url = 'https://raw.githubusercontent.com/codeforamerica/ohana-api/master/data/sample-csv/addresses.csv'
p = pd.read_csv(url)


id  location_id  ... postal_code country
0    1            1  ...       94063      US
1    2            2  ...       94401      US
2    3            3  ...       94403      US
3    4            4  ...       94401      US
4    5            5  ...       94401      US
5    6            6  ...  94025-9881      US
6    7            7  ...       94025      US
7    8            8  ...  94025-9881      US
8    9            9  ...       94063      US
9   10           10  ...       94063      US
10  11           11  ...       94061      US
11  12           12  ...       94063      US
12  13           13  ...       94065      US
13  14           14  ...       94063      US
14  15           15  ...       94110      US
15  16           16  ...       94087      US
16  17           17  ...       94080      US
17  18           18  ...       94063      US
18  19           19  ...       94403      US
19  20           21  ...       94002      US
20  21           22  ...       94103      US

[21 rows x 8 columns]

In [21]:
p.head(3)

id  location_id              address_1  ... state_province postal_code country
0   1            1  2600 Middlefield Road  ...             CA       94063      US
1   2            2       24 Second Avenue  ...             CA       94401      US
2   3            3       24 Second Avenue  ...             CA       94403      US

[3 rows x 8 columns]

In [22]:
p.tail(6)

id  location_id  ... postal_code country
15  16           16  ...       94087      US
16  17           17  ...       94080      US
17  18           18  ...       94063      US
18  19           19  ...       94403      US
19  20           21  ...       94002      US
20  21           22  ...       94103      US

[6 rows x 8 columns]

In [23]:
p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   id              21 non-null     int64 
 1   location_id     21 non-null     int64 
 2   address_1       21 non-null     object
 3   address_2       2 non-null      object
 4   city            21 non-null     object
 5   state_province  21 non-null     object
 6   postal_code     21 non-null     object
 7   country         21 non-null     object
dtypes: int64(2), object(6)
memory usage: 1.4+ KB


In [29]:
city = p['city']
city
my_list = list(city)
my_dict = dict(city)
my_dict

{0: 'Redwood City',
 1: 'San Mateo',
 2: 'San Mateo',
 3: 'San Mateo',
 4: 'San Mateo',
 5: 'Menlo Park',
 6: 'Menlo Park',
 7: 'Menlo Park',
 8: 'Redwood City',
 9: 'Redwood City',
 10: 'Redwood City',
 11: 'Redwood City',
 12: 'Redwood City',
 13: 'Redwood City',
 14: 'San Francisco',
 15: 'Sunnyvale',
 16: 'South San Francisco',
 17: 'Redwood City',
 18: 'San Mateo',
 19: 'Belmont',
 20: 'San Francisco'}

In [30]:
p

id  location_id  ... postal_code country
0    1            1  ...       94063      US
1    2            2  ...       94401      US
2    3            3  ...       94403      US
3    4            4  ...       94401      US
4    5            5  ...       94401      US
5    6            6  ...  94025-9881      US
6    7            7  ...       94025      US
7    8            8  ...  94025-9881      US
8    9            9  ...       94063      US
9   10           10  ...       94063      US
10  11           11  ...       94061      US
11  12           12  ...       94063      US
12  13           13  ...       94065      US
13  14           14  ...       94063      US
14  15           15  ...       94110      US
15  16           16  ...       94087      US
16  17           17  ...       94080      US
17  18           18  ...       94063      US
18  19           19  ...       94403      US
19  20           21  ...       94002      US
20  21           22  ...       94103      US

[21 rows x 8 columns]

In [38]:
p[p['location_id'] >= 10]['city']

9            Redwood City
10           Redwood City
11           Redwood City
12           Redwood City
13           Redwood City
14          San Francisco
15              Sunnyvale
16    South San Francisco
17           Redwood City
18              San Mateo
19                Belmont
20          San Francisco
Name: city, dtype: object